[workspace]
resolver = "2"
members = [
    "zenobuf-core",
    "zenobuf-macros",
    "zenobuf-cli",
    "zenobuf-examples",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Zenobuf Team"]
description = "A simpler ROS-like framework in Rust"
license = "MIT OR Apache-2.0"
