# This is a cargo-deny configuration file
# See https://embarkstudios.github.io/cargo-deny/

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
    "RUSTSEC-2024-0436", # paste - no longer maintained
    "RUSTSEC-2023-0071"  # rsa - Marvin Attack vulnerability
]

[licenses]
version = 2
# We want to allow any OSI-approved license
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0",
    "EPL-2.0"
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
